### ISSUE TITLE
What is the relation between Game and Position and Variation?

### ISSUE THREAD

**Issue by willemmulder** [yo35/kokopu#17]
Hi, it might be just me but I'm having trouble understanding the relation between Game, Position and Variation.

I would consider a Game to be the 'total state' of a game, with e.g. the initial Position, the played moves, all resulting Positions and the current Position. However I can only find the initialPosition there... 

What is the proper way to set up a Game, set a board, then play some moves and then get hold of all the previous Positions (and current Position) through the Game object?

And what is a Variation meant for? Do we need to use it or is it just an internal thing? 

Thanks!

**Comment by yo35** [comment]
Hi,
Sorry for the late reply.

The two main objects are `Position` and `Game`:
- `Position` describes the state of the board, i.e. which piece is on which square, who is about to play, the castle rights, and the en-passant column if any.
- `Game` describes the total state of the game as you put it, i.e. the played moved, the corresponding positions, the metadata associated to the game (names of the players, date, etc...), and the annotations associated to the moves (text comments, alternative moves considered by the annotator, etc...).

Since a `Game` object can hold several alternative moves proposed by an annotator, the moves are represented through a tree-like structure (rather than a linear-like structure, as it would be the case if only the move actually played were considered). There are two secondary objects used to represent this tree structure:
- `Node` represents one move + the annotations associated to this move. It gives you access to the positions before and after the move is played (see methods [Node#positionBefore()](https://kokopu.yo35.org/docs/Node.html#positionBefore) and [Node#position()](https://kokopu.yo35.org/docs/Node.html#position)). It also gives you access to the following move in the game (see [Node#next()](https://kokopu.yo35.org/docs/Node.html#next)), and the alternative moves -- aka. the variations -- if any (see [Node#variations()](https://kokopu.yo35.org/docs/Node.html#variations)).
- `Variation` represents a sequence of `Node` objects, aka a sequence of moves. A `Game` object holds a so-called "main variation" (see [Game#mainVariation()](https://kokopu.yo35.org/docs/Game.html#mainVariation)) that is the root of the tree structure.

You can create a game from scratch as follows:
```
var game = new Game();

var current = game.mainVariation(); // `current` points at a `Variation` object here
current = current.play('e4'); // `current` points at a `Node` object from now on
current = current.play('e5');

// Let's introduce an alternative to move 1...e5
var alternative1 = current.addVariation(); // `alternative1` points at a `Variation` object here
alternative1 = alternative1.play('c5'); // `alternative1` points at a `Node` object from now on
alternative1 = alternative1.play('Nf3');

// Back to the main variation
current = current.play('Bc4');
current = current.play('Nc6');
current = current.play('Qh5');
current = current.play('Nf6');
current = current.play('Qxf7#');
current.comment('That is the Scholar\'s Mate');
game.result('1-0');
```

**Comment by willemmulder** [comment]
Hi @yo35 thanks for the extensive reply; that makes a lot of sense!

A few remaining questions:

- It makes sense to have a .play() function on a Node, as it will generate a new Node and 'move forward' in the game. But if I do a .play() on a position, that's not representing a 'real' move, right? It's like a helper function to set up a Position, correct?
- I'm trying to make a Chess Engine that supports UCI. I've just implemented the first version at https://github.com/willemmulder/SuperSimpleChessEngine. What I see is that the UCI protocol sends me a completely new FEN string after every opponent-move. How would I use that information to create a new Node? Do I have to figure out the actual move and then do node.play(move) or is there another way to just create a new Node based on the new FEN string?

Thanks! :-)

**Comment by willemmulder** [comment]
Oh, and would you consider adding this information to the docs as well?

**Comment by yo35** [comment]
Hi,

1) The `.play()` function invokes on a `Position` updates the underlying position according to the given move. For instance:
```
var pos = new kokopu.Position();
console.log(pos.ascii()); // Shows the usual starting position, that is:

// +---+---+---+---+---+---+---+---+
// | r | n | b | q | k | b | n | r |
// +---+---+---+---+---+---+---+---+
// | p | p | p | p | p | p | p | p |
// +---+---+---+---+---+---+---+---+
// |   |   |   |   |   |   |   |   |
// +---+---+---+---+---+---+---+---+
// |   |   |   |   |   |   |   |   |
// +---+---+---+---+---+---+---+---+
// |   |   |   |   |   |   |   |   |
// +---+---+---+---+---+---+---+---+
// |   |   |   |   |   |   |   |   |
// +---+---+---+---+---+---+---+---+
// | P | P | P | P | P | P | P | P |
// +---+---+---+---+---+---+---+---+
// | R | N | B | Q | K | B | N | R |
// +---+---+---+---+---+---+---+---+
// w KQkq -

pos.play('e4');
console.log(pos.ascii()); // Now `pos` represents the position after move e4:

// +---+---+---+---+---+---+---+---+
// | r | n | b | q | k | b | n | r |
// +---+---+---+---+---+---+---+---+
// | p | p | p | p | p | p | p | p |
// +---+---+---+---+---+---+---+---+
// |   |   |   |   |   |   |   |   |
// +---+---+---+---+---+---+---+---+
// |   |   |   |   |   |   |   |   |
// +---+---+---+---+---+---+---+---+
// |   |   |   |   | P |   |   |   |
// +---+---+---+---+---+---+---+---+
// |   |   |   |   |   |   |   |   |
// +---+---+---+---+---+---+---+---+
// | P | P | P | P |   | P | P | P |
// +---+---+---+---+---+---+---+---+
// | R | N | B | Q | K | B | N | R |
// +---+---+---+---+---+---+---+---+
// b KQkq -

```

2. I'm not sure to understand why you need to create a `Game` object to implement a UCI-compatible chess engine. My understanding of the problem is that when the engine is asked to analyse a position (i.e. when it receives the UCI command `position [fen | startpos ] moves`), you can create a new `Position` object from scratch based on the arguments of the UCI command. I don't see the point of keeping the whole history in a `Game` object.
By the way, inferring which move has been played between two -- supposedly consecutive -- positions defined through FEN strings is not trivial, and is not implemented in Kokopu.

3. The example you gives to create a `Game` starting from a custom position is supposed to work. What is wrong with it?

4. I'll probably enrich the examples in the documentation at some point.

**Comment by yo35** [comment]
Example showing how to create a `Game` object from scratch added to the documentation:
https://kokopu.yo35.org/docs/tutorial-04_set_up_game.html

**Comment by willemmulder** [comment]
Hi, 

Sorry for the late reply and thanks so much for your answers and updates to the documentation!

1. Yes, so `Position` holds a position and using` .play(...)` updates it, but if I wanted to capture/register an actual move, then I'd use `.play()` on a `Node`, right?
2. Good point. I think I simply wanted to have a central overview of the total game (on the engine side), with all the moves played, and I'd figure Game is the correct object for that. But in retrospect, an engine just needs to process a position and come up with the best move. And the UI will keep track of the total game for us.
3. Great, thanks!
4. Perfect! :-)

Thanks for the good work!

**Comment by yo35** [comment]
Regarding your first point, if you to capture all the history of a game, then you must create a `Game` object, retrieve its main variation, and register all the moves by invoking [Node.play()](https://kokopu.yo35.org/docs/Node.html#play) iteratively as shown in example https://kokopu.yo35.org/docs/tutorial-04_set_up_game.html

**Comment by willemmulder** [comment]
Exactly, thanks! 😃
