### ISSUE TITLE
pgn tags

### ISSUE THREAD

**Issue by vladmandic** [yo35/kokopu#33]
currently library supports parsing of standard **PGN Seven Tag Roster**:
- `Event`, `Site`, `Date`, `Round`, `White`, `Black`, `Result`  

and adds couple of more of non-standard tags:
- `Annotator`, `BlackTitle`, `WhiteTitle`

per [PGN specs](https://docslib.org/doc/1205996/portable-game-notation-specification-and-implementation-guide) a tag pair section can be anything as long as its in format of `[` `<key>` `"<value>"` `]`  

why are there 3 very specific non-standard tags and there is no support for other tags as they are used by many chess sites?

for example, i'm writing a game annotator and would like to add a **termination** reason as its commonly found.

**Comment by vladmandic** [comment]
proposed solution in pr #34

**Comment by yo35** [comment]
The reason why all non-standard tags are not supported is that -- by definition -- they are non-standard. Thus, support for them is added on a per need basis, assuming their use and meaning have been de facto standardized by several operators - chess softwares, websites... As a matter of fact, a support for the `[Termination "..."]` tag could be implemented, as it is explicitly mentioned in the [PGN specs](https://ia802908.us.archive.org/26/items/pgn-standard-1994-03-12/PGN_standard_1994-03-12.txt) among the possible extra tags (see section 9.8.1), and is used by several chess sites (lichess...).

Still, I don't want to offer a generic uncontrolled support for all possible pairs of key-value strings. Several reasons for that:
- some tags may accept only some specific values, e.g. integer for `WhiteElo`/`BlackElo`, format-specific for `Date`, value among a predefined finite set (aka an enum) for `Result`, format-specific as well for `ECO` (if this one is implemented one day)...
- some tags may require some specific traitement, e.g. `SetUp`, `FEN` and `Variant` must be handled together for consistency, `PlyCount` should be read-only (because computed from the move section) if it were implemented...

**Comment by vladmandic** [comment]
I agree that everything that is already correctly handled should not be overwritten by generic tags - and its easy to add such exclusion.

But...PGN specs you've quoted are from 1994 while the latest [2020](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm) version has many more tags listed in that section.
And both 1994 and 2020 PGN specs versions **explicitly allow generic tags** under misc. So why not allow them as such?

And yes, ideally all documented supplemental tags should be handled exactly as intended. But that's a big ask. 
And as each is handled, that tag can be added to exluclusion list for generic tags.
Lets take `Termination` as example - if you add it next week, it can be added to list of prohibited generic tags.

And lets talk about my specific use case - automatic game annotation. I read a PGN file, run automatic analysis using UCI engine, ECO opening database, Syzygy endgame database, etc. - and write it back with annotations.  

From current list of *Supplemental tag names*, I'd like to use at the minimum: `Opening`, ``Variation`, `SubVariation`, `ECO`, `PlyCount`, `TimeControl`, `Termination`  
Plus few additional misc tag that would allow to write notes such as "draw due to insufficient material" as that is a) allowed under misc tags, b) no such proposed tag currently exists  

So if there is are no generic tags, how can I can achieve this? I'd like to contribute back to this library, but if it cannot meet the requirements, alternative is just to run a fork.

**Comment by yo35** [comment]
> PGN specs you've quoted are from 1994 while the latest [2020](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm) version has many more tags listed in that section.

Just to mention: the [PGN specs](https://ia802908.us.archive.org/26/items/pgn-standard-1994-03-12/PGN_standard_1994-03-12.txt) I refer to and [yours](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm) are the same - up to HTML formatting. As far as I known, the PGN format specification has not evolved since 1994.

Again, I'm not closed to add support for additional tags. Typically, `Opening`, `Variation`, `SubVariation` and `Termination` are mentioned in the PGN specs, and could be implemented as additional tags accepting any string value (just as `Annotator`). `ECO` is definitely legitimate, with string values validated with `/[A-E][0-9][0-9]/` or equivalent. `TimeControl` is also definitely relevant, although the values accepted here must go through a more complex validation scheme (see the PGN specs, section 9.6.1) that would require additional discussion.

Regarding `PlyCount`, there is no need for a setter on class `Game` for that, as it can be deduced from the move tree. An option can be added to the `pgnWrite(..)` function to control whether the corresponding tags are written to the PGN or not.

**Comment by yo35** [comment]
I've just pushed a new version, that supports `ECO`, `Opening`, `Variation`, `SubVariation`, `Termination` and `PlyCount`.

**Comment by vladmandic** [comment]
thanks, closing this issue.
