### ISSUE TITLE
It would be handy if Database supported Iterable

### ISSUE THREAD

**Issue by JeffML** [yo35/kokopu#36]
Then I wouldn't have to iterate "by hand" using `for (let i=0; i < db.gameCount(); i++)`; it would also allow me to use other things, like map-reduce functions.

**Comment by yo35** [comment]
That's a good idea. Just, I need to think of how ill-formed PGN files should be handled. Typically: what happens to the iterator if the `i`-th game in the database cannot be parsed (i.e. what happens in the case where `database.game(i)` would throw a `InvalidPGN` exception).

Possible answers:
- Catch the `InvalidPGN` exceptions internally in the iterator, and iterate only on the valid games. Cons: in this case, the `i`-th element returned by the iterator may not correspond to `database.game(i)` (index mismatch).
- Make the iterator return a function with signature `() => Game`, instead of a `Game` instance. Cons: this is a bit convoluted to use, including in the cases where it is known that the underlying PGN is not ill-formed.
- ...

I still need to think of it, to be sure to make the right choice.

**Comment by JeffML** [comment]
Have the iterator return a Game or Error object? This should be possible in TypeScript. 

Implementing games() as a generator might be an option.  If an exception is thrown and caught, by my reading the caller should be able to continue calling the generator after the exception:

[Advanced Generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#advanced_generators)

I'm not sure what happens in a for...of loop when an exception is thrown and caught in the loop...can it just continue? Perhaps.

**Comment by yo35** [comment]
Done in version 4.4.0, just released.

`Database` itself is not an Iterable, but has a new `games()` method that returns an Iterable. See [documentation](https://kokopu.yo35.org/docs/current/classes/Database.html#games) for more details.

The behavior chosen with regard to the unparsable games that may be present in the PGN files is to ignore them. As a consequence, the `i`-th element returned by the iterator may not correspond to `database.game(i)`, and the number of elements returned by the iterator may be lower than `database.gameCount()`. I've opted for this policy so that the iterator is as easy to use as possible on the caller side.

**Comment by JeffML** [comment]
Ok. That loses information regarding which PGN was unparseable, but that is
of no consequence to me and expect it will be a rare occurrence anyway.

Thank you.
