### ISSUE TITLE
Chess variations

### ISSUE THREAD

**Issue by SwanX1** [yo35/kokopu#39]
Is it possible to extend the classes to create new chess variants other than ones in the library? For example, Chess.com's solo chess.

**Comment by yo35** [comment]
Hi,

Kokopu does not support implementation of new chess variants by 3rd party libraries: the way it is designed, the set of supported non-standard chess variants is hard-coded, and can only be extended by modifying the core Kokopu classes (class [`Position`](https://kokopu.yo35.org/docs/current/classes/Position.html) especially).

Regarding Solo chess, it may not be simple to implement, since the typology of the game is quite different from the one of regular chess: it's a single-player game, and each piece have a hidden state corresponding to the number of times it has already performed a capture...

**Comment by SwanX1** [comment]
Does that mean it's possible anyways (by extending the Position class), or is it easier to fork the package?

**Comment by yo35** [comment]
Depending on what you want to do, my guess is that it should be easier to create your own class representing a Solo chess game. This class may contain a `Position` instance to generate the possible moves (with method [`Position.getAttacks(..)`](https://kokopu.yo35.org/docs/current/classes/Position.html#getAttacks) for instance).
