### ISSUE TITLE
Errors with pgn from lichess

### ISSUE THREAD

**Issue by shooter01** [yo35/kokopu#42]
I am trying to export this study from lichess and import inside my app
https://lichess.org/study/8dnqBWj0
but get an error:

`Unknown chess game variant (From Position).`

then I am trying to avoid this error with

`multerText = multerText.replace(/"From Position"/g, 'regular');`

but then get an error

`Missing or invalid PGN game header value`

**Comment by yo35** [comment]
Double-quotes are missing in the replacement string. Should be:

```
multerText = multerText.replace(/"From Position"/g, '"regular"');
```

**Comment by shooter01** [comment]
works, thanks, do you consider to add `From Position` option as a possible ?

**Comment by yo35** [comment]
In my opinion, the problem is on lichess' side, and the PGN files generated by lichess with `[Variant "From Position"]` are invalid: the `[Variant "..."]` tag is supposed to contain the name of the chess game variant if the underlying game follows non-standard chess rules. On the other hand, `"From Position"` is use by lichess -- from what I understand -- as a sort of indication of how the PGN has been generated, which is a completely different kind of information.
