### ISSUE TITLE
How does one access the moves/variations/comments/etc. of a Game object?

### ISSUE THREAD

**Issue by danegraphics** [yo35/kokopu#9]
I couldn't find anything in the documentation that allows one to access the content of a game object, such as the moves, the variations, the comments, etc. Only the names of the players and other things like that.

I need to be able to load PGNs, look at them/add comments and variations to them/etc, and then export the modified PGNs after.

How would I do that?

**Comment by danegraphics** [comment]
Turns out both Node and Variation are exposed and can be accessed, but only after calling `Game.mainVariation()`.

**Comment by yo35** [comment]
Hi,
I'm opened to any suggestion that would improve the API exposed by the `Game` and `Variation` objects.

**Comment by danegraphics** [comment]
@yo35 - It would be very useful to be able to navigate the variation object through an array of nodes.

Instead of doing multiple `next()` calls to reach a certain move, you can simply do something like `variation.nodeList()[7]` to reach the 8th ply in a variation.

**Comment by yo35** [comment]
Done in version 1.3.0.

WARNING: in order to provide a consistent API, I had to slightly break the API of the `Node` object, in particular regarding functions `Node#next()` and `Node#play(..)`. Now, these methods always return a new instance of `Node`, instead of returning a pointer to `this`.

In other words, as of 1.3.0, a given `Node` instance always points at the same move within a `Variation`, which is also more understandable in my opinion.
